services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: 'donntu_library'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - donntu_library_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d donntu_library']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'

volumes:
  donntu_library_postgres_data: